version: "3.8"

services:
  web:
    build: ./web
    ports:
      - "5173:5173"
    volumes:
      - ./web:/app
      - /app/node_modules
    depends_on:
      - server
    networks:
      - app-network

  server:
    build: ./server
    ports:
      - "3000:3000"
    volumes:
      - ./server:/app
      - /app/node_modules
    depends_on:
      - mongodb
      # - redis
    networks:
      - app-network

  mongodb:
    image: mongo:6.0
    container_name: starwars-mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - app-network

  redis:
    image: redis:7
    container_name: starwars-redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - app-network
      
volumes:
  mongo_data:
  redis_data:

networks:
  app-network:
    driver: bridge
